/*********************************************************************
 * Software License Agreement (GPLv3)
 *
 *  GS1 related lookup tables
 *  Copyright (c) 2025-2026, Bob Mottram
 *  bob@libreserver.org
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program.  If not, see <https://www.gnu.org/licenses/>.
 *
 *********************************************************************/

/* See https://navigator.gs1.org/edi/codelist-details?name=PackageTypeCode&version=9 */
char * package_type_code[] = {
    "1A", "Drum, steel",
    "1B", "Drum, aluminium",
    "1D", "Drum, plywood",
    "1F", "Container, flexible",
    "1G", "Drum, fibre",
    "1W", "Drum, wooden",
    "200", "Pallet with dimensions 80cm X 60cm",
    "201", "Pallet with dimensions 80cm X 120cm",
    "202", "Pallet with dimensions 100cm X 120cm",
    "203", "Pallet with dimensions 60cm X 40cm",
    "204", "Pallet with dimensions 40cm X 30cm",
    "205", "Pallet with dimensions 80cm X 120cm made of a synthetic material for hygienic reasons",
    "206", "Pallet with dimensions 100cm X 120cm made of a synthetic material for hygienic reasons",
    "210", "Pallet provided by the wholesaler",
    "211", "Pallet with dimensions 80cm X 100cm",
    "212", "Pallet with dimensions 60cm X 100cm",
    "2C", "Barrel, wooden",
    "3A", "Jerrican, steel",
    "3H", "Jerrican, plastic",
    "43", "Bag, super bulk",
    "44", "Bag, polybag",
    "4A", "Box, steel",
    "4B", "Box, aluminium",
    "4C", "Box, natural wood",
    "4D", "Box, plywood",
    "4F", "Box, reconstituted wood",
    "4G", "Box, fibreboard",
    "4H", "Box, plastic",
    "5H", "Bag, woven plastic",
    "5L", "Bag, textile",
    "5M", "Bag, paper",
    "6H", "Composite packaging, plastic receptacle",
    "6P", "Composite packaging, glass receptacle",
    "7A", "Case, car",
    "7B", "Case, wooden",
    "8", "Oneway pallet",
    "8A", "Pallet, wooden",
    "8B", "Crate, wooden",
    "8C", "Bundle, wooden",
    "9", "Returnable pallet",
    "AA", "Intermediate bulk container, rigid plastic",
    "AB", "Receptacle, fibre",
    "AC", "Receptacle, paper",
    "AD", "Receptacle, wooden",
    "AF", "Pallet, modular, collars 80cm X 60cm",
    "AG", "Pallet, shrinkwrapped",
    "AH", "Pallet, 100cm X 110cm",
    "AI", "Clamshell",
    "AJ", "Cone",
    "AL", "Ball",
    "AM", "Ampoule, non-protected",
    "AP", "Ampoule, protected",
    "APE", "Aluminium packed",
    "AT", "Atomizer",
    "AV", "Capsule",
    "B4", "Belt",
    "BB", "Bobbin",
    "BC", "Bottlecrate / bottlerack",
    "BD", "Board",
    "BE", "Bundle",
    "BF", "Balloon, non-protected",
    "BG", "Bag",
    "BGE", "Large bag, pallet sized",
    "BH", "Bunch",
    "BI", "Bin",
    "BJ", "Bucket",
    "BK", "Basket",
    "BL", "Bale, compressed",
    "BM", "Basin",
    "BME", "Blister pack",
    "BN", "Bale, non-compressed",
    "BO", "Bottle, non-protected, cylindrical",
    "BP", "Balloon, protected",
    "BQ", "Bottle, protected cylindrical",
    "BR", "Bar",
    "BRI", "Brick",
    "BS", "Bottle, non-protected, bulbous",
    "BT", "Bolt",
    "BU", "Butt",
    "BV", "Bottle, protected bulbous",
    "BW", "Box, for liquids",
    "BX", "Box",
    "BY", "Board, in bundle/bunch/truss",
    "BZ", "Bars, in bundle/bunch/truss",
    "CA", "Can, rectangular",
    "CB", "Crate, beer",
    "CBL", "Container bottle like",
    "CC", "Churn",
    "CCE", "Cardboard carrier",
    "CD", "Can, with handle and spout",
    "CE", "Creel",
    "CF", "Coffer",
    "CG", "Cage",
    "CH", "Chest",
    "CI", "Canister",
    "CJ", "Coffin",
    "CK", "Cask",
    "CL", "Coil",
    "CM", "Card",
    "CN", "Container, not otherwise specified as transport equipment",
    "CO", "Carboy, non-protected",
    "CP", "Carboy, protected",
    "CQ", "Cartridge",
    "CR", "Crate",
    "CS", "Case",
    "CT", "Carton",
    "CU", "Cup",
    "CV", "Cover",
    "CW", "Cage, roll",
    "CX", "Can, cylindrical",
    "CY", "Cylinder",
    "CZ", "Canvas",
    "DA", "Crate, multiple layer, plastic",
    "DB", "Crate, multiple layer, wooden",
    "DC", "Crate, multiple layer, cardboard",
    "DG", "Cage, Commonwealth Handling Equipment Pool (CHEP)",
    "DH", "Box, Commonwealth Handling Equipment Pool (CHEP), Eurobox",
    "DI", "Drum, iron",
    "DJ", "Demijohn, non-protected",
    "DK", "Crate, bulk, cardboard",
    "DL", "Crate, bulk, plastic",
    "DM", "Crate, bulk, wooden",
    "DN", "Dispenser",
    "DP", "Demijohn, protected",
    "DPE", "Display package",
    "DR", "Drum",
    "DS", "Tray, one layer no cover, plastic",
    "DT", "Tray, one layer no cover, wooden",
    "DU", "Tray, one layer no cover, polystyrene",
    "DV", "Tray, one layer no cover, cardboard",
    "DW", "Tray, two layers no cover, plastic tray",
    "DX", "Tray, two layers no cover, wooden",
    "DY", "Tray, two layers no cover, cardboard",
    "E1", "Meat container with dimensions 60cm X 40cm X 12.5cm",
    "E2", "Meat container with dimensions 60cm X 40cm X 20cm",
    "E3", "Meat container with dimensions 60cm X 40cm X 30cm",
    "EC", "Bag, plastic",
    "ED", "Case, with pallet base",
    "EE", "Case, with pallet base, wooden",
    "EF", "Case, with pallet base, cardboard",
    "EG", "Case, with pallet base, plastic",
    "EH", "Case, with pallet base, metal",
    "EI", "Case, isothermic",
    "EN", "Envelope",
    "FB", "Flexibag",
    "FC", "Crate, fruit",
    "FD", "Crate, framed",
    "FE", "Flexitank",
    "FI", "Firkin",
    "FL", "Flask",
    "FO", "Footlocker",
    "FOB", "Folding box",
    "FP", "Filmpack",
    "FPE", "Foil packed",
    "FR", "Frame",
    "FT", "Foodtainer",
    "FW", "Cart, flatbed",
    "FX", "Bag, flexible container",
    "GB", "Bottle, gas",
    "GI", "Girder",
    "GL", "Container, gallon",
    "GR", "Receptacle, glass",
    "GU", "Tray, containing horizontally stacked flat items",
    "GY", "Bag, gunny",
    "GZ", "Girders, in bundle/bunch/truss",
    "HA", "Basket, with handle, plastic",
    "HB", "Basket, with handle, wooden",
    "HC", "Basket, with handle, cardboard",
    "HG", "Hogshead",
    "HN", "Hanger",
    "HR", "Hamper",
    "IA", "Package, display, wooden",
    "IB", "Package, display, cardboard",
    "IC", "Package, display, plastic",
    "ID", "Package, display, metal",
    "IE", "Package, show",
    "IF", "Package, flow",
    "IG", "Package, paper wrapped",
    "IH", "Drum, plastic",
    "IK", "Package, cardboard, with bottle grip-holes",
    "IL", "Tray, rigid, lidded stackable",
    "IN", "Ingot",
    "IZ", "Ingots, in bundle/bunch/truss",
    "JB", "Bag, jumbo",
    "JC", "Jerrican, rectangular",
    "JG", "Jug",
    "JR", "Jar",
    "JT", "Jutebag",
    "JY", "Jerrican, cylindrical",
    "KG", "Keg",
    "KI", "Kit",
    "LAB", "Labeled package",
    "LE", "Luggage",
    "LG", "Log",
    "LT", "Lot",
    "LU", "Lug",
    "LV", "Liftvan",
    "LZ", "Logs, in bundle/bunch/truss",
    "MA", "Crate, metal",
    "MB", "Bag, multiply",
    "MC", "Crate, milk",
    "ME", "Container, metal",
    "MPE", "Multipack",
    "MR", "Receptacle, metal",
    "MS", "Sack, multi-wall",
    "MT", "Mat",
    "MW", "Receptacle, plastic wrapped",
    "MX", "Matchbox",
    "NA", "Not available",
    "NE", "Unpacked or unpackaged",
    "NF", "Unpacked or unpackaged, single unit",
    "NG", "Unpacked or unpackaged, multiple units",
    "NS", "Nest",
    "NT", "Net",
    "NU", "Net, tube, plastic",
    "NV", "Net, tube, textile",
    "OA", "Pallet, CHEP 40cm X 60cm",
    "OB", "Pallet, CHEP 80cm X 120cm",
    "OC", "Pallet, CHEP 100cm X 120cm",
    "OD", "Australian standard pallet of dimensions 115.5cm X 116.5cm",
    "OE", "Pallet of dimensions 110cm X 110cm",
    "OF", "Pallet equivalent shipping platform of unknown dimensions or unknown weight",
    "OK", "Block",
    "OPE", "Oxygen packed",
    "OT", "Octabin",
    "OU", "Container, outer",
    "P2", "Pan",
    "PA", "Packet",
    "PAE", "Paper",
    "PB", "Pallet, box",
    "PC", "Parcel",
    "PD", "Pallet, modular, collars 80cm X 100cm",
    "PE", "Pallet, modular, collars 80cm X 120cm",
    "PF", "Pen",
    "PG", "Plate",
    "PH", "Pitcher",
    "PI", "Pipe",
    "PJ", "Punnet",
    "PK", "Package",
    "PL", "Pail",
    "PLP", "Peel pack",
    "PN", "Plank",
    "PO", "Pouch",
    "POP", "Cone shaped paper wrapper",
    "PP", "Piece",
    "PPE", "Polypropylene bag",
    "PR", "Receptacle, plastic",
    "PT", "Pot",
    "PU", "Tray",
    "PUE", "Tray packed in plastic",
    "PV", "Pipes, in bundle/bunch/truss",
    "PX", "Pallet",
    "PY", "Plates, in bundle/bunch/truss",
    "PZ", "Planks, in bundle/bunch/truss",
    "QA", "Drum, steel, non-removable head",
    "QB", "Drum, steel, removable head",
    "QC", "Drum, aluminium, non-removable head",
    "QD", "Drum, aluminium, removable head",
    "QF", "Drum, plastic, non-removable head",
    "QG", "Drum, plastic, removable head",
    "QH", "Barrel, wooden, bung type",
    "QJ", "Barrel, wooden, removable head",
    "QK", "Jerrican, steel, non-removable head",
    "QL", "Jerrican, steel, removable head",
    "QM", "Jerrican, plastic, non-removable head",
    "QN", "Jerrican, plastic, removable head",
    "QP", "Box, wooden, natural wood, ordinary",
    "QQ", "Box, wooden, natural wood, with sift proof walls",
    "QR", "Box, plastic, expanded",
    "QS", "Box, plastic, solid",
    "RB1", "A wheeled pallet with raised rim 81cm X 67cm X 135cm",
    "RB2", "A Wheeled pallet with raised rim 81cm X 72cm X 135cm",
    "RB3", "Wheeled pallet with raised rim. 81cm X 60cm X 16cm",
    "RCB", "Two sided cage on wheels with fixing strap 900cm x 770cm x 1513cm",
    "RD", "Rod",
    "RG", "Ring",
    "RJ", "Rack, clothing hanger",
    "RK", "Rack",
    "RL", "Reel",
    "RO", "Roll",
    "RT", "Rednet",
    "RZ", "Rods, in bundle/bunch/truss",
    "S1", "Reusable crate with dimensions 60cm X 40cm X 21.1cm",
    "SA", "Sack",
    "SB", "Slab",
    "SC", "Crate, shallow",
    "SD", "Spindle",
    "SE", "Sea-chest",
    "SEC", "Article Surveillance",
    "SH", "Sachet",
    "SI", "Skid",
    "SK", "Case, skeleton",
    "SL", "Slipsheet",
    "SM", "Sheetmetal",
    "SO", "Spool",
    "SP", "Sheet, plastic wrapping",
    "SS", "Case, steel",
    "ST", "Sheet",
    "STL", "Stick",
    "SU", "Suitcase",
    "SV", "Envelope, steel",
    "SW", "Shrinkwrapped",
    "SX", "Set",
    "SY", "Sleeve",
    "SZ", "Sheets, in bundle/bunch/truss",
    "T1", "Tablet",
    "TB", "Tub",
    "TC", "Tea-chest",
    "TD", "Tube, collapsible",
    "TE", "Tyre",
    "TEV", "Tamper evident package",
    "TG", "Tank container, generic",
    "THE", "Three pack",
    "TI", "Tierce",
    "TK", "Tank, rectangular",
    "TL", "Tub, with lid",
    "TN", "Tin",
    "TO", "Tun",
    "TR", "Trunk",
    "TRE", "Trolley",
    "TS", "Truss",
    "TT", "Bag, tote",
    "TTE", "Tube, standing",
    "TU", "Tube",
    "TV", "Tube, with nozzle",
    "TW", "Pallet, triwall",
    "TWE", "Two pack",
    "TY", "Tank, cylindrical",
    "TZ", "Tubes, in bundle/bunch/truss",
    "UC", "Uncaged",
    "UN", "Unit",
    "UUE", "Tube net",
    "VA", "Vat",
    "VG", "Bulk, gas (at 1031 mbar and 15°C)",
    "VI", "Vial",
    "VK", "Vanpack",
    "VL", "Bulk, liquid",
    "VN", "Vehicle",
    "VO", "Bulk, solid, large particles (nodules)",
    "VP", "Vacuum-packed",
    "VQ", "Bulk, liquefied gas (at abnormal temperature/pressure)",
    "VR", "Bulk, solid, granular particles (grains)",
    "VS", "Bulk, scrap metal",
    "VY", "Bulk, solid, fine particles (powders)",
    "WA", "Intermediate bulk container",
    "WB", "Wickerbottle",
    "WC", "Intermediate bulk container, steel",
    "WD", "Intermediate bulk container, aluminium",
    "WF", "Intermediate bulk container, metal",
    "WG", "Intermediate bulk container, steel, pressurised > 10 kpa",
    "WH", "Intermediate bulk container, aluminium, pressurised > 10 kpa",
    "WJ", "Intermediate bulk container, metal, pressure 10 kpa",
    "WK", "Intermediate bulk container, steel, liquid",
    "WL", "Intermediate bulk container, aluminium, liquid",
    "WM", "Intermediate bulk container, metal, liquid",
    "WN", "Intermediate bulk container, woven plastic, without coat/liner",
    "WP", "Intermediate bulk container, woven plastic, coated",
    "WQ", "Intermediate bulk container, woven plastic, with liner",
    "WR", "Intermediate bulk container, woven plastic, coated and liner",
    "WRP", "Wrapper",
    "WS", "Intermediate bulk container, plastic film",
    "WT", "Intermediate bulk container, textile without coat/liner",
    "WU", "Intermediate bulk container, natural wood, with inner liner",
    "WV", "Intermediate bulk container, textile, coated",
    "WW", "Intermediate bulk container, textile, with liner",
    "WX", "Intermediate bulk container, textile, coated and liner",
    "WY", "Intermediate bulk container, plywood, with inner liner",
    "WZ", "Intermediate bulk container, reconstituted wood, with inner liner",
    "X11", "Banded package",
    "X12", "Cardboard package with grip holes for bottles",
    "X15", "Oneway pallet with dimensions 80cm X 60cm",
    "X16", "Oneway pallet with dimensions 80cm X 120cm",
    "X17", "Oneway pallet with dimensions 100cm X 120cm",
    "X18", "Pallet with exceptional dimensions",
    "X19", "Parcel with exceptional dimensions",
    "X20", "Wooden pallet 120cm X 120cm",
    "X3", "Standard stack of stones",
    "XA", "Bag, woven plastic, without inner coat/liner",
    "XB", "Bag, woven plastic, sift proof",
    "XC", "Bag, woven plastic, water resistant",
    "XD", "Bag, plastics film",
    "XF", "Bag, textile, without inner coat/liner",
    "XG", "Bag, textile, sift proof",
    "XH", "Bag, textile, water resistant",
    "XJ", "Bag, paper, multi-wall",
    "XK", "Bag, paper, multi-wall, water resistant",
    "YA", "Composite packaging, plastic receptacle in steel drum",
    "YB", "Composite packaging, plastic receptacle in steel crate box",
    "YC", "Composite packaging, plastic receptacle in aluminium drum",
    "YD", "Composite packaging, plastic receptacle in aluminium crate",
    "YF", "Composite packaging, plastic receptacle in wooden box",
    "YG", "Composite packaging, plastic receptacle in plywood drum",
    "YH", "Composite packaging, plastic receptacle in plywood box",
    "YJ", "Composite packaging, plastic receptacle in fibre drum",
    "YK", "Composite packaging, plastic receptacle in fibreboard box",
    "YL", "Composite packaging, plastic receptacle in plastic drum",
    "YM", "Composite packaging, plastic receptacle in solid plastic box",
    "YN", "Composite packaging, glass receptacle in steel drum",
    "YP", "Composite packaging, glass receptacle in steel crate box",
    "YQ", "Composite packaging, glass receptacle in aluminium drum",
    "YR", "Composite packaging, glass receptacle in aluminium crate",
    "YS", "Composite packaging, glass receptacle in wooden box",
    "YT", "Composite packaging, glass receptacle in plywood drum",
    "YV", "Composite packaging, glass receptacle in wickerwork hamper",
    "YW", "Composite packaging, glass receptacle in fibre drum",
    "YX", "Composite packaging, glass receptacle in fibreboard box",
    "YY", "Composite packaging, glass receptacle in expandable plastic pack",
    "YZ", "Composite packaging, glass receptacle in solid plastic pack",
    "ZA", "Intermediate bulk container, paper, multi-wall",
    "ZB", "Bag, large",
    "ZC", "Intermediate bulk container, paper, multi-wall, water resistant",
    "ZD", "Intermediate bulk container, rigid plastic, with structural equipment, solids",
    "ZF", "Intermediate bulk container, rigid plastic, freestanding, solids",
    "ZG", "Intermediate bulk container, rigid plastic, with structural equipment, pressurised",
    "ZH", "Intermediate bulk container, rigid plastic, freestanding, pressurised",
    "ZJ", "Intermediate bulk container, rigid plastic, with structural equipment, liquids",
    "ZK", "Intermediate bulk container, rigid plastic, freestanding, liquids",
    "ZL", "Intermediate bulk container, composite, rigid plastic, solids",
    "ZM", "Intermediate bulk container, composite, flexible plastic, solids",
    "ZN", "Intermediate bulk container, composite, rigid plastic, pressurised",
    "ZP", "Intermediate bulk container, composite, flexible plastic, pressurised",
    "ZQ", "Intermediate bulk container, composite, rigid plastic, liquids",
    "ZR", "Intermediate bulk container, composite, flexible plastic, liquids",
    "ZS", "Intermediate bulk container, composite",
    "ZT", "Intermediate bulk container, fibreboard",
    "ZU", "Intermediate bulk container, flexible",
    "ZV", "Intermediate bulk container, metal, other than steel",
    "ZW", "Intermediate bulk container, natural wood",
    "ZX", "Intermediate bulk container, plywood",
    "ZY", "Intermediate bulk container, reconstituted wood",
    "ZZ", "Mutually defined"
};

/* https://en.wikipedia.org/wiki/List_of_GS1_country_codes */
char * gs1_company_prefix[] = {
    "0000000", "", "Used to issue Restricted Ciruculation Numbers within a company",
    "0000001", "0000099", "Unused to avoid collision with GTIN-8",
    "00001", "00009", "GS1 US",
    "0001", "0009", "GS1 US",
    "001", "019", "GS1 US",
    "020", "029", "Used to issue Restricted Circulation Numbers within a geographic region (MO defined)",
    "030", "039", "GS1 US",
    "040", "049", "Used to issue GS1 Restricted Circulation Numbers within a company",
    "050", "059", "GS1 US reserved for future use",
    "060", "139", "GS1 US",
    "200", "299", "Used to issue GS1 Restricted Circulation Numbers within a geographic region (MO defined)",
    "300", "379", "GS1 France",
    "380", "", "GS1 Bulgaria",
    "383", "", "GS1 Slovenija",
    "385", "", "GS1 Croatia",
    "387", "", "GS1 BIH (Bosnia-Herzegovina)",
    "389", "", "GS1 Montenegro",
    "400", "440", "GS1 Germany",
    "450", "459", "GS1 Japan",
    "490", "499", "GS1 Japan",
    "460", "469", "GS1 Russia",
    "470", "", "GS1 Kyrgyzstan",
    "471", "", "GS1 Chinese Taipei",
    "474", "", "GS1 Estonia",
    "475", "", "GS1 Latvia",
    "476", "", "GS1 Azerbaijan",
    "477", "", "GS1 Lithuania",
    "478", "", "GS1 Uzbekistan",
    "479", "", "GS1 Sri Lanka",
    "480", "", "GS1 Philippines",
    "481", "", "GS1 Belarus",
    "482", "", "GS1 Ukraine",
    "483", "", "GS1 Turkmenistan",
    "484", "", "GS1 Moldova",
    "485", "", "GS1 Armenia",
    "486", "", "GS1 Georgia",
    "487", "", "GS1 Kazakstan",
    "488", "", "GS1 Tajikistan",
    "489", "", "GS1 Hong Kong, China",
    "500", "509", "GS1 UK",
    "520", "521", "GS1 Association Greece",
    "528", "", "GS1 Lebanon",
    "529", "", "GS1 Cyprus",
    "530", "", "GS1 Albania",
    "531", "", "GS1 Macedonia",
    "535", "", "GS1 Malta",
    "539", "", "GS1 Ireland",
    "540", "549", "GS1 Belgium & Luxembourg",
    "560", "", "GS1 Portugal",
    "569", "", "GS1 Iceland",
    "570", "579", "GS1 Denmark",
    "590", "", "GS1 Poland",
    "594", "", "GS1 Romania",
    "599", "", "GS1 Hungary",
    "600", "601", "GS1 South Africa",
    "603", "", "GS1 Ghana",
    "604", "", "GS1 Senegal",
    "605", "", "Managed by GS1 Global Office for future MO",
    "606", "", "Managed by GS1 Global Office for future MO",
    "607", "", "Managed by GS1 Global Office for future MO",
    "608", "", "GS1 Bahrain",
    "609", "", "GS1 Mauritius",
    "610", "", "Managed by GS1 Global Office for future MO",
    "611", "", "GS1 Morocco",
    "613", "", "GS1 Algeria",
    "614", "", "Managed by GS1 Global Office for future MO",
    "615", "", "GS1 Nigeria",
    "616", "", "GS1 Kenya",
    "617", "", "GS1 Cameroon",
    "618", "", "GS1 Côte d'Ivoire",
    "619", "", "GS1 Tunisia",
    "620", "", "GS1 Tanzania",
    "621", "", "GS1 Syria",
    "622", "", "GS1 Egypt",
    "623", "", "GS1 Brunei",
    "624", "", "GS1 Libya",
    "625", "", "GS1 Jordan",
    "626", "", "GS1 Iran",
    "627", "", "GS1 Kuwait",
    "628", "", "GS1 Saudi Arabia",
    "629", "", "GS1 Emirates",
    "630", "", "GS1 Qatar",
    "640", "649", "GS1 Finland",
    "690", "699", "GS1 China",
    "700", "709", "GS1 Norway",
    "729", "", "GS1 Israel",
    "730", "739", "GS1 Sweden",
    "740", "", "GS1 Guatemala",
    "741", "", "GS1 El Salvador",
    "742", "", "GS1 Honduras",
    "743", "", "GS1 Nicaragua",
    "744", "", "GS1 Costa Rica",
    "745", "", "GS1 Panama",
    "746", "", "GS1 Republica Dominicana",
    "750", "", "GS1 Mexico",
    "754", "755", "GS1 Canada",
    "758", "", "Managed by GS1 Global Office for future MO",
    "759", "", "GS1 Venezuela",
    "760", "769", "GS1 Schweiz, Suisse, Svizzera",
    "770", "771", "GS1 Colombia",
    "773", "", "GS1 Uruguay",
    "775", "", "GS1 Peru",
    "777", "", "GS1 Bolivia",
    "778", "779", "GS1 Argentina",
    "780", "", "GS1 Chile",
    "784", "", "GS1 Paraguay",
    "786", "", "GS1 Ecuador",
    "789", "790", "GS1 Brazil",
    "800", "839", "GS1 Italy",
    "840", "849", "GS1 Spain",
    "850", "", "GS1 Cuba",
    "858", "", "GS1 Slovakia",
    "859", "", "GS1 Czech",
    "860", "", "GS1 Serbia",
    "865", "", "GS1 Mongolia",
    "867", "", "GS1 North Korea",
    "868", "869", "GS1 Turkey",
    "870", "879", "GS1 Netherlands",
    "880", "", "GS1 South Korea",
    "883", "", "GS1 Myanmar",
    "884", "", "GS1 Cambodia",
    "885", "", "GS1 Thailand",
    "888", "", "GS1 Singapore",
    "890", "", "GS1 India",
    "893", "", "GS1 Vietnam",
    "894", "", "Managed by GS1 Global Office for future MO",
    "896", "", "GS1 Pakistan",
    "899", "", "GS1 Indonesia",
    "900", "919", "GS1 Austria",
    "930", "939", "GS1 Australia",
    "940", "949", "GS1 New Zealand",
    "950", "", "GS1 Global Office",
    "951", "", "Global Office - General Manager Number, see Note 2",
    "952", "", "Used for demonstrations and examples of the GS1 system"
    "955", "", "GS1 Malaysia",
    "958", "", "GS1 Macau, China",
    "960", "969", "Global Office - GTIN-8, see note 3",
    "977", "", "Serial publications (ISSN)",
    "978", "979", "Bookland (ISBN)",
    "980", "", "Refund receipts",
    "981", "984", "GS1 coupon identification for common currency areas",
    "99", "", "GS1 coupon identification"
};

/* https://en.wikipedia.org/wiki/ISO_3166-1_numeric
   Used for "T3783 target market country codes" */
char * iso3166_country_codes[] = {
    "Afghanistan", "", "004",
    "Albania", "", "008",
    "Antarctica", "", "010",
    "Algeria", "", "012",
    "Andorra", "", "020",
    "Angola", "", "024",
    "Antigua and Barbuda", "", "028",
    "Azerbaijan", "", "031",
    "Argentina", "", "032",
    "Australia", "", "036",
    "Austria", "", "040",
    "Bahamas", "", "044",
    "Bahrain", "", "048",
    "Bangladesh", "", "050",
    "Armenia", "", "051",
    "Barbados", "", "052",
    "Belgium", "", "056",
    "Bermuda", "", "060",
    "Bhutan", "", "064",
    "Bolivia", "", "068",
    "Bosnia and Herzegovina", "", "070",
    "Botswana", "", "072",
    "Bouvet Island", "", "074",
    "Brazil", "", "076",
    "Belize", "", "084",
    "British Indian Ocean Territory", "", "086",
    "Brunei Darussalam", "", "096",
    "Bulgaria", "", "100",
    "Burundi", "", "108",
    "Belarus", "", "112",
    "Cambodia", "", "116",
    "Cameroon", "", "120",
    "Canada", "", "124",
    "Cabo Verde", "", "132",
    "Cayman Islands", "", "136",
    "Central African Republic", "", "140",
    "Chad", "", "148",
    "Chile", "", "152",
    "China", "", "156",
    "Christmas Island", "", "162",
    "Cocos (Keeling) Islands", "", "166",
    "Colombia", "", "170",
    "Comoros", "", "174",
    "Congo", "", "178",
    "Cook Islands", "", "184",
    "Costa Rica", "", "188",
    "Croatia", "", "191",
    "Cuba", "", "192",
    "Cyprus", "", "196",
    "Czechia", "", "203",
    "Benin", "", "204",
    "Denmark", "", "208",
    "Dominica", "", "212",
    "Dominican Republic", "", "214",
    "Ecuador", "", "218",
    "El Salvador", "", "222",
    "Equatorial Guinea", "", "226",
    "Ethiopia", "", "231",
    "Eritrea", "", "232",
    "Estonia", "", "233",
    "Faroe Islands", "", "234",
    "Falkland Islands", "", "238",
    "Fiji", "", "242",
    "Finland", "", "246",
    "Åland Islands", "", "248",
    "France", "", "250",
    "French Guiana", "", "254",
    "French Polynesia", "", "258",
    "French Southern Territories", "", "260",
    "Djibouti", "", "262",
    "Gabon", "", "266",
    "Georgia", "", "268",
    "Gambia", "", "270",
    "Germany", "", "276",
    "Ghana", "", "288",
    "Gibraltar", "", "292",
    "Greece", "", "300",
    "Greenland", "", "304",
    "Grenada", "", "308",
    "Guadeloupe", "", "312",
    "Guam", "", "316",
    "Guatemala", "", "320",
    "Guinea", "", "324",
    "Guyana", "", "328",
    "Haiti", "", "332",
    "Heard Island and McDonald Islands", "", "334",
    "Holy See", "", "336",
    "Honduras", "", "340",
    "Hong Kong", "", "344",
    "Hungary", "", "348",
    "Iceland", "", "352",
    "India", "", "356",
    "Indonesia", "", "360",
    "Iran", "", "364",
    "Iraq", "", "368",
    "Ireland", "", "372",
    "Israel", "", "376",
    "Italy", "", "380",
    "Côte d'Ivoire", "", "384",
    "Jamaica", "", "388",
    "Japan", "", "392",
    "Jersey", "JEY", "832",
    "Jordan", "JOR", "400",
    "Kazakhstan", "KAZ", "398",
    "Kenya", "KEN", "404",
    "Kiribati", "KIR", "296",
    "North Korea", "PRK", "408",
    "South Korea", "KOR", "410",
    "Kuwait", "KWT", "414",
    "Kyrgyzstan", "KGZ", "417",
    "Laos", "LAO", "418",
    "Latvia", "LVA", "428",
    "Lebanon", "LBN", "422",
    "Lesotho", "LSO", "426",
    "Liberia", "LBR", "430",
    "Libya", "LBY", "434",
    "Liechtenstein", "LIE", "438",
    "Lithuania", "LTU", "440",
    "Luxembourg", "LUX", "442",
    "Macau", "MAC", "446",
    "Madagascar", "MDG", "450",
    "Malawi", "MWI", "454",
    "Malaysia", "MYS", "458",
    "Maldives", "MDV", "462",
    "Mali", "MLI", "466",
    "Malta", "MLT", "470",
    "Marshall Islands", "MHL", "584",
    "Martinique", "MTQ", "474",
    "Mauritania", "MRT", "478",
    "Mauritius", "MUS", "480",
    "Mayotte", "MYT", "175",
    "Mexico", "MEX", "484",
    "Federated States of Micronesia", "FSM", "583",
    "Moldova", "MDA", "498",
    "Monaco", "MCO", "492",
    "Mongolia",   "MNG", "496",
    "Montenegro", "MNE", "499",
    "Montserrat", "MSR", "500",
    "Morocco", "MAR", "504",
    "Mozambique", "MOZ", "508",
    "Myanmar", "MMR", "104",
    "Namibia", "NAM", "516",
    "Nauru", "NRU", "520",
    "Nepal", "NPL", "524",
    "Netherlands", "NLD", "528",
    "New Caledonia", "NCL", "540",
    "New Zealand", "NZL", "554",
    "Nicaragua", "NIC", "558",
    "Niger", "NER", "562",
    "Nigeria", "NGA", "566",
    "Niue", "NIU", "570",
    "Norfolk Island", "NFK", "574",
    "North Korea", "MKD", "807",
    "Northern Mariana Islands", "MNP", "580",
    "Norway", "NOR", "578",
    "Oman", "OMN", "512",
    "Pakistan", "PAK", "586",
    "Palau", "PLW", "585",
    "Palestine", "PSE", "275",
    "Panama", "PAN", "591",
    "Papua New Guinea", "PNG", "598",
    "Paraguay",   "PRY", "600",
    "Peru", "PER", "604",
    "Philippines", "PHL", "608",
    "Pitcairn Islands", "PCN", "612",
    "Poland", "POL", "616",
    "Portugal", "PRT", "620",
    "Puerto Rico", "PRI", "630",
    "Qatar", "QAT", "634",
    "Réunion", "REU", "638",
    "Romania", "ROU", "642",
    "Russia", "RUS", "643",
    "Rwanda", "RWA", "646",
    "Saint Barthélemy", "BLM", "652",
    "Saint Helena", "SHN", "654",
    "Saint Kitts and Nevis", "KNA", "659",
    "Saint Lucia", "LCA", "662",
    "Collectivity of Saint Martin", "MAF", "663",
    "Saint Pierre and Miquelon", "SPM", "666",
    "Saint Vincent and the Grenadines", "VCT", "670",
    "Samoa", "WSM", "882",
    "San Marino", "SMR", "674",
    "São Tomé and Príncipe", "STP", "678",
    "Saudi Arabia", "SAU", "682",
    "Senegal", "SEN", "686",
    "Serbia", "SRB", "688",
    "Seychelles", "SYC", "690",
    "Sierra Leone", "SLE", "694",
    "Singapore", "SGP", "702",
    "Sint Maarten", "SXM", "534",
    "Slovakia", "SVK", "703",
    "Slovenia", "SVN", "705",
    "Solomon Islands", "SLB", "090",
    "Somalia", "SOM", "706",
    "South Africa", "ZAF", "710",
    "South Georgia and the South Sandwich Islands", "SGS", "239",
    "South Sudan", "SSD", "728",
    "Spain", "ESP", "724",
    "Sri Lanka", "LKA", "144",
    "Sudan", "SDN", "729",
    "Suriname", "SUR", "740",
    "Svalbard", "SJM", "744",
    "Sweden", "SWE", "752",
    "Switzerland", "CHE", "756",
    "Syria", "SYR", "760",
    "Taiwan", "TWN", "158",
    "Tajikistan", "TJK", "762",
    "Tanzania", "TZA", "834",
    "Thailand", "THA", "764",
    "Timor-Leste", "TLS", "626",
    "Togo", "TGO", "768",
    "Tokelau", "TKL", "772",
    "Tonga", "TON", "776",
    "Trinidad and Tobago", "TTO", "780",
    "Tunisia", "TUN", "788",
    "Turkey", "TUR", "792",
    "Turkmenistan", "TKM", "795",
    "Turks and Caicos Islands", "TCA", "796",
    "Tuvalu", "TUV", "798",
    "Uganda", "UGA", "800",
    "Ukraine", "UKR", "804",
    "United Arab Emirates", "ARE", "784",
    "United Kingdom", "GBR", "826",
    "United States", "UMI", "581",
    "United States", "USA", "840",
    "Uruguay", "URY", "858",
    "Uzbekistan", "UZB", "860",
    "Vanuatu", "VUT", "548",
    "Venezuela", "VEN", "862",
    "Vietnam", "VNM", "704",
    "British Virgin Islands", "VGB", "092",
    "United States Virgin Islands", "VIR", "850",
    "Wallis and Futuna", "WLF", "876",
    "Western Sahara", "ESH", "732",
    "Yemen", "YEM", "887",
    "Zambia", "ZMB", "894",
    "Zimbabwe", "ZWE", "716"
};

char * iso4217_currency_codes[] = {
    "AFGHANISTAN",         "Afghani",               "AFN",       "971",
    "ALBANIA",             "Lek",                   "ALL",       "008",
    "ALGERIA",             "Algerian Dinar",        "DZD",       "012",
    "AMERICAN SAMOA",      "US Dollar",             "USD",       "840",
    "ANDORRA",             "Euro",                  "EUR",       "978",
    "ANGOLA",                "Kwanza",                "AOA",       "973",
    "ANGUILLA",            "East Caribbean Dollar", "XCD",       "951",
    "ANTIGUA AND BARBUDA", "East Caribbean Dollar", "XCD",       "951",
    "ARGENTINA",           "Argentine Peso",        "ARS",       "032",
    "ARMENIA",             "Armenian Dram",         "AMD",       "051",
    "ARUBA",               "Aruban Florin",         "AWG",       "533",
    "AUSTRALIA",           "Australian Dollar",     "AUD",       "036",
    "AUSTRIA",             "Euro",                  "EUR",       "978",
    "AZERBAIJAN",          "Azerbaijanian Manat",   "AZN",       "944",
    "BAHAMAS (THE)",       "Bahamian Dollar",       "BSD",       "044",
    "BAHRAIN",             "Bahraini Dinar",        "BHD",       "048",
    "BANGLADESH",          "Taka",                  "BDT",       "050",
    "BARBADOS",            "Barbados Dollar",       "BBD",       "052",
    "BELARUS",             "Belarussian Ruble",     "BYN",       "933",
    "BELGIUM",             "Euro",                  "EUR",       "978",
    "BELIZE",              "Belize Dollar",         "BZD",       "084",
    "BENIN",               "CFA Franc BCEAO",       "XOF",       "952",
    "BERMUDA",             "Bermudian Dollar",      "BMD",       "060",
    "BHUTAN",              "Ngultrum",              "BTN",       "064",
    "BHUTAN",              "Indian Rupee",          "INR",       "356",
    "BOLIVIA (PLURINATIONAL STATE OF)", "Boliviano", "BOB", "068",
    "BOLIVIA (PLURINATIONAL STATE OF)", "Mvdol",    "BOV",       "984",
    "BONAIRE, SINT EUSTATIUS AND SABA", "US Dollar", "USD",      "840",
    "BOSNIA AND HERZEGOVINA", "Convertible Mark",   "BAM",       "977",
    "BOTSWANA",            "Pula",                  "BWP",       "072",
    "BOUVET ISLAND",       "Norwegian Krone",       "NOK",       "578",
    "BRAZIL",              "Brazilian Real",        "BRL",       "986",
    "BRITISH INDIAN OCEAN TERRITORY (THE)", "US Dollar", "USD",  "840",
    "BRUNEI DARUSSALAM",   "Brunei Dollar",         "BND",       "096",
    "BULGARIA",            "Bulgarian Lev",         "BGN",       "975",
    "BURKINA FASO",        "CFA Franc BCEAO",       "XOF",       "952",
    "BURUNDI",             "Burundi Franc",         "BIF",       "108",
    "CABO VERDE",          "Cabo Verde Escudo",     "CVE",       "132",
    "CAMBODIA",            "Riel",                  "KHR",       "116",
    "CAMEROON",            "CFA Franc BEAC",        "XAF",       "950",
    "CANADA",              "Canadian Dollar",       "CAD",       "124",
    "CAYMAN ISLANDS (THE)", "Cayman Islands Dollar", "KYD",      "136",
    "CENTRAL AFRICAN REPUBLIC (THE)", "CFA Franc BEAC", "XAF",   "950",
    "CHAD",                "CFA Franc BEAC",        "XAF",       "950",
    "CHILE",               "Unidad de Fomento",     "CLF",       "990",
    "CHILE",               "Chilean Peso",          "CLP",       "152",
    "CHINA",               "Yuan Renminbi",         "CNY",       "156",
    "CHRISTMAS ISLAND",    "Australian Dollar",     "AUD",       "036",
    "COCOS (KEELING) ISLANDS (THE)", "Australian Dollar", "AUD", "036",
    "COLOMBIA",            "Colombian Peso",        "COP",       "170",
    "COLOMBIA",            "Unidad de Valor Real",  "COU",       "970",
    "COMOROS (THE)",       "Comoro Franc",          "KMF",       "174",
    "CONGO (THE DEMOCRATIC REPUBLIC OF THE)", "Congolese Franc", "CDF", "976",
    "CONGO (THE)",         "CFA Franc BEAC",        "XAF",       "950",
    "COOK ISLANDS (THE)",  "New Zealand Dollar",    "NZD",       "554",
    "COSTA RICA",          "Costa Rican Colon",     "CRC",       "188",
    "CROATIA",             "Euro",                  "EUR",       "978",
    "CUBA",                "Peso Convertible",      "CUC",       "931",
    "CUBA",                "Cuban Peso",            "CUP",       "192",
    "CURAÇAO",             "Caribbean Guilder",     "XCG",       "532",
    "CYPRUS",              "Euro",                  "EUR",       "978",
    "CZECH REPUBLIC (THE)", "Czech Koruna",         "CZK",       "203",
    "CÔTE D'IVOIRE",       "CFA Franc BCEAO",       "XOF",       "952",
    "DENMARK",             "Danish Krone",          "DKK",       "208",
    "DJIBOUTI",            "Djibouti Franc",        "DJF",       "262",
    "DOMINICA",            "East Caribbean Dollar", "XCD",       "951",
    "DOMINICAN REPUBLIC (THE)", "Dominican Peso",   "DOP",       "214",
    "ECUADOR",             "US Dollar",             "USD",       "840",
    "EGYPT",               "Egyptian Pound",        "EGP",       "818",
    "EL SALVADOR",         "El Salvador Colon",     "SVC",       "222",
    "EL SALVADOR",         "US Dollar",             "USD",       "840",
    "EQUATORIAL GUINEA",   "CFA Franc BEAC",        "XAF",       "950",
    "ERITREA",             "Nakfa",                 "ERN",       "232",
    "ESTONIA",             "Euro",                  "EUR",       "978",
    "ETHIOPIA",            "Ethiopian Birr",        "ETB",       "230",
    "EUROPEAN UNION",      "Euro",                  "EUR",       "978",
    "FALKLAND ISLANDS (THE)", "Falkland Islands Pound", "FKP",   "238",
    "FAROE ISLANDS (THE)", "Danish Krone",          "DKK",       "208",
    "FIJI",                "Fiji Dollar",           "FJD",       "242",
    "FINLAND",             "Euro",                  "EUR",       "978",
    "FRANCE",              "Euro",                  "EUR",       "978",
    "FRENCH GUIANA",       "Euro",                  "EUR",       "978",
    "FRENCH POLYNESIA",    "CFP Franc",             "XPF",       "953",
    "FRENCH SOUTHERN TERRITORIES (THE)", "Euro",    "EUR",       "978",
    "GABON",               "CFA Franc BEAC",        "XAF",       "950",
    "GAMBIA (THE)",        "Dalasi",                "GMD",       "270",
    "GEORGIA",             "Lari",                  "GEL",       "981",
    "GERMANY",             "Euro",                  "EUR",       "978",
    "GHANA",               "Ghana Cedi",            "GHS",       "936",
    "GIBRALTAR",           "Gibraltar Pound",       "GIP",       "292",
    "GREECE",              "Euro",                  "EUR",       "978",
    "GREENLAND",           "Danish Krone",          "DKK",       "208",
    "GRENADA",             "East Caribbean Dollar", "XCD",       "951",
    "GUADELOUPE",          "Euro",                  "EUR",       "978",
    "GUAM",                "US Dollar",             "USD",       "840",
    "GUATEMALA",           "Quetzal",               "GTQ",       "320",
    "GUERNSEY",            "Pound Sterling",        "GBP",       "826",
    "GUINEA",              "Guinea Franc",          "GNF",       "324",
    "GUINEA-BISSAU",       "CFA Franc BCEAO",       "XOF",       "952",
    "GUYANA",              "Guyana Dollar",         "GYD",       "328",
    "HAITI",               "Gourde",                "HTG",       "332",
    "HAITI",               "US Dollar",             "USD",       "840",
    "HEARD ISLAND AND McDONALD ISLANDS", "Australian Dollar", "AUD", "036",
    "HOLY SEE (THE)",      "Euro",                  "EUR",       "978",
    "HONDURAS",            "Lempira",               "HNL",       "340",
    "HONG KONG",           "Hong Kong Dollar",      "HKD",       "344",
    "HUNGARY",             "Forint",                "HUF",       "348",
    "ICELAND",             "Iceland Krona",         "ISK",       "352",
    "INDIA",               "Indian Rupee",          "INR",       "356",
    "INDONESIA",           "Rupiah",                "IDR",       "360",
    "INTERNATIONAL MONETARY FUND (IMF)", "SDR (Special Drawing Right)", "XDR", "960",
    "IRAN (ISLAMIC REPUBLIC OF)", "Iranian Rial", "IRR", "364",
    "IRAQ",                "Iraqi Dinar",           "IQD",       "368",
    "IRELAND",             "Euro",                  "EUR",       "978",
    "ISLE OF MAN",         "Pound Sterling",        "GBP",       "826",
    "ISRAEL",              "New Israeli Sheqel",    "ILS",       "376",
    "ITALY",               "Euro",                  "EUR",       "978",
    "JAMAICA",             "Jamaican Dollar",       "JMD",       "388",
    "JAPAN",               "Yen",                   "JPY",       "392",
    "JERSEY",              "Pound Sterling",        "GBP",       "826",
    "JORDAN",              "Jordanian Dinar",       "JOD",       "400",
    "KAZAKHSTAN",          "Tenge",                 "KZT",       "398",
    "KENYA",               "Kenyan Shilling",       "KES",       "404",
    "KIRIBATI",            "Australian Dollar",     "AUD",       "036",
    "KOREA (THE DEMOCRATIC PEOPLE’S REPUBLIC OF)", "North Korean Won", "KPW", "408",
    "KOREA (THE REPUBLIC OF)", "Won",               "KRW",       "410",
    "KUWAIT",              "Kuwaiti Dinar",         "KWD",       "414",
    "KYRGYZSTAN",          "Som",                   "KGS",       "417",
    "LAO PEOPLE’S DEMOCRATIC REPUBLIC (THE)", "Kip", "LAK",      "418",
    "LATVIA",              "Euro",                  "EUR",       "978",
    "LEBANON",             "Lebanese Pound",        "LBP",       "422",
    "LESOTHO",             "Loti",                  "LSL",       "426",
    "LESOTHO",             "Rand",                  "ZAR",       "710",
    "LIBERIA",             "Liberian Dollar",       "LRD",       "430",
    "LIBYA",               "Libyan Dinar",          "LYD",       "434",
    "LIECHTENSTEIN",       "Swiss Franc",           "CHF",       "756",
    "LITHUANIA",           "Euro",                  "EUR",       "978",
    "LUXEMBOURG",          "Euro",                  "EUR",       "978",
    "MACAO",               "Pataca",                "MOP",       "446",
    "MADAGASCAR",          "Malagasy Ariary",       "MGA",       "969",
    "MALAWI",              "Kwacha",                "MWK",       "454",
    "MALAYSIA",            "Malaysian Ringgit",     "MYR",       "458",
    "MALDIVES",            "Rufiyaa",               "MVR",       "462",
    "MALI",                "CFA Franc BCEAO",       "XOF",       "952",
    "MALTA",               "Euro",                  "EUR",       "978",
    "MARSHALL ISLANDS (THE)", "US Dollar",          "USD",       "840",
    "MARTINIQUE",          "Euro",                  "EUR",       "978",
    "MAURITANIA",          "Ouguiya",               "MRU",       "929",
    "MAURITIUS",           "Mauritius Rupee",       "MUR",       "480",
    "MAYOTTE",             "Euro",                  "EUR",       "978",
    "MEMBER COUNTRIES OF THE AFRICAN DEVELOPMENT BANK GROUP", "ADB Unit of Account", "XUA", "965",
    "MEXICO",              "Mexican Peso",          "MXN",       "484",
    "MEXICO",              "Mexican Unidad de Inversion (UDI)", "MXV", "979",
    "MICRONESIA (FEDERATED STATES OF)", "US Dollar", "USD",      "840",
    "MOLDOVA (THE REPUBLIC OF)", "Moldovan Leu",    "MDL",       "498",
    "MONACO",              "Euro",                  "EUR",       "978",
    "MONGOLIA",            "Tugrik",                "MNT",       "496",
    "MONTENEGRO",          "Euro",                  "EUR",       "978",
    "MONTSERRAT",          "East Caribbean Dollar", "XCD",       "951",
    "MOROCCO",             "Moroccan Dirham",       "MAD",       "504",
    "MOZAMBIQUE", "Mozambique Metical",             "MZN",       "943",
    "MYANMAR",             "Kyat",                  "MMK",       "104",
    "NAMIBIA",             "Namibia Dollar",        "NAD",       "516",
    "NAMIBIA",             "Rand",                  "ZAR",       "710",
    "NAURU",               "Australian Dollar",     "AUD",       "036",
    "NEPAL",               "Nepalese Rupee",        "NPR",       "524",
    "NETHERLANDS (THE)",   "Euro",                  "EUR",       "978",
    "NEW CALEDONIA",       "CFP Franc",             "XPF",       "953",
    "NEW ZEALAND",         "New Zealand Dollar",    "NZD",       "554",
    "NICARAGUA",           "Cordoba Oro",           "NIO",       "558",
    "NIGER (THE)",         "CFA Franc BCEAO",       "XOF",       "952",
    "NIGERIA",             "Naira",                 "NGN",       "566",
    "NIUE",                "New Zealand Dollar",    "NZD",       "554",
    "NORFOLK ISLAND",      "Australian Dollar",     "AUD",       "036",
    "NORTHERN MARIANA ISLANDS (THE)", "US Dollar",  "USD",       "840",
    "NORWAY",              "Norwegian Krone",       "NOK",       "578",
    "OMAN",                "Rial Omani",            "OMR",       "512",
    "PAKISTAN",            "Pakistan Rupee",        "PKR",       "586",
    "PALAU",               "US Dollar",             "USD",       "840",
    "PANAMA",              "Balboa",                "PAB",       "590",
    "PANAMA",              "US Dollar",             "USD",       "840",
    "PAPUA NEW GUINEA",    "Kina",                  "PGK",       "598",
    "PARAGUAY",            "Guarani",               "PYG",       "600",
    "PERU",                "Nuevo Sol",             "PEN",       "604",
    "PHILIPPINES (THE)",   "Philippine Peso",       "PHP",       "608",
    "PITCAIRN",            "New Zealand Dollar",    "NZD",       "554",
    "POLAND",              "Zloty",                 "PLN",       "985",
    "PORTUGAL",            "Euro",                  "EUR",       "978",
    "PUERTO RICO",         "US Dollar",             "USD",       "840",
    "QATAR",               "Qatari Rial",           "QAR",       "634",
    "REPUBLIC OF NORTH MACEDONIA", "Denar",         "MKD",       "807",
    "ROMANIA",             "Romanian Leu",          "RON",       "946",
    "RUSSIAN FEDERATION (THE)", "Russian Ruble",    "RUB",       "643",
    "RWANDA",              "Rwanda Franc",          "RWF",       "646",
    "RÉUNION",             "Euro",                  "EUR",       "978",
    "SAINT BARTHÉLEMY",    "Euro",                  "EUR",       "978",
    "SAINT HELENA, ASCENSION AND TRISTAN DA CUNHA", "Saint Helena Pound", "SHP", "654",
    "SAINT KITTS AND NEVIS", "East Caribbean Dollar", "XCD",     "951",
    "SAINT LUCIA",         "East Caribbean Dollar", "XCD",       "951",
    "SAINT MARTIN (FRENCH PART)", "Euro",           "EUR",       "978",
    "SAINT PIERRE AND MIQUELON", "Euro",            "EUR",       "978",
    "SAINT VINCENT AND THE GRENADINES", "East Caribbean Dollar", "XCD", "951",
    "SAMOA",               "Tala",                  "WST",       "882",
    "SAN MARINO",          "Euro",                  "EUR",       "978",
    "SAO TOME AND PRINCIPE", "Dobra",               "STN",       "930",
    "SAUDI ARABIA",        "Saudi Riyal",           "SAR",       "682",
    "SENEGAL",             "CFA Franc BCEAO",       "XOF",       "952",
    "SERBIA",              "Serbian Dinar",         "RSD",       "941",
    "SEYCHELLES",          "Seychelles Rupee",      "SCR",       "690",
    "SIERRA LEONE",        "Leone",                 "SLE",       "925",
    "SINGAPORE",           "Singapore Dollar",      "SGD",       "702",
    "SINT MAARTEN (DUTCH PART)", "Caribbean guilder", "XCG",     "532",
    "SISTEMA UNITARIO DE COMPENSACION REGIONAL DE PAGOS \"SUCRE\"", "Sucre", "XSU", "994",
    "SLOVAKIA",            "Euro",                  "EUR",       "978",
    "SLOVENIA",            "Euro",                  "EUR",       "978",
    "SOLOMON ISLANDS",     "Solomon Islands Dollar", "SBD",      "090",
    "SOMALIA",             "Somali Shilling",       "SOS",       "706",
    "SOUTH AFRICA",        "Rand",                  "ZAR",       "710",
    "SOUTH SUDAN",         "South Sudanese Pound",  "SSP",       "728",
    "SPAIN",               "Euro",                  "EUR",       "978",
    "SRI LANKA",           "Sri Lanka Rupee",       "LKR",       "144",
    "SUDAN (THE)",         "Sudanese Pound",        "SDG",       "938",
    "SURINAME",            "Surinam Dollar",        "SRD",       "968",
    "SVALBARD AND JAN MAYEN", "Norwegian Krone",    "NOK",       "578",
    "SWAZILAND",           "Lilangeni",             "SZL",       "748",
    "SWEDEN",              "Swedish Krona",         "SEK",       "752",
    "SWITZERLAND",         "WIR Euro",              "CHE",       "947",
    "SWITZERLAND",         "Swiss Franc",           "CHF",       "756",
    "SWITZERLAND",         "WIR Franc",             "CHW",       "948",
    "SYRIAN ARAB REPUBLIC", "Syrian Pound",         "SYP",       "760",
    "TAIWAN (PROVINCE OF CHINA)", "New Taiwan Dollar", "TWD",    "901",
    "TAJIKISTAN",          "Somoni",                "TJS",       "972",
    "TANZANIA, UNITED REPUBLIC OF", "Tanzanian Shilling", "TZS", "834",
    "THAILAND",            "Baht",                  "THB",       "764",
    "TIMOR-LESTE",         "US Dollar",             "USD",       "840",
    "TOGO",                "CFA Franc BCEAO",       "XOF",       "952",
    "TOKELAU",             "New Zealand Dollar",    "NZD",       "554",
    "TONGA",               "Pa’anga",               "TOP",       "776",
    "TRINIDAD AND TOBAGO", "Trinidad and Tobago Dollar", "TTD",  "780",
    "TUNISIA",             "Tunisian Dinar",        "TND",       "788",
    "TURKEY",              "Turkish Lira",          "TRY",       "949",
    "TURKMENISTAN",        "Turkmenistan New Manat", "TMT",      "934",
    "TURKS AND CAICOS ISLANDS (THE)", "US Dollar",  "USD",       "840",
    "TUVALU",              "Australian Dollar",     "AUD",       "036",
    "UGANDA",              "Uganda Shilling",       "UGX",       "800",
    "UKRAINE",             "Hryvnia",               "UAH",       "980",
    "UNITED ARAB EMIRATES (THE)", "UAE Dirham",     "AED",       "784",
    "UNITED KINGDOM OF GREAT BRITAIN AND NORTHERN IRELAND (THE)", "Pound Sterling", "GBP", "826",
    "UNITED STATES MINOR OUTLYING ISLANDS (THE)", "US Dollar", "USD", "840",
    "UNITED STATES OF AMERICA (THE)", "US Dollar",  "USD",       "840",
    "UNITED STATES OF AMERICA (THE)", "US Dollar (Next day)", "USN", "997",
    "URUGUAY",             "Uruguay Peso en Unidades Indexadas (URUIURUI)", "UYI", "940",
    "URUGUAY",             "Peso Uruguayo",         "UYU",       "858",
    "UZBEKISTAN",          "Uzbekistan Sum",        "UZS",       "860",
    "VANUATU",             "Vatu",                  "VUV",       "548",
    "VENEZUELA (BOLIVARIAN REPUBLIC OF)", "Bolivar", "VEF",      "937",
    "VENEZUELA (BOLIVARIAN REPUBLIC OF)", "Bolivar", "VED",      "926",
    "VIET NAM",            "Dong",                  "VND",       "704",
    "VIRGIN ISLANDS (BRITISH)", "US Dollar",        "USD",       "840",
    "VIRGIN ISLANDS (U.S.)", "US Dollar",           "USD",       "840",
    "WALLIS AND FUTUNA",   "CFP Franc",             "XPF",       "953",
    "WESTERN SAHARA",      "Moroccan Dirham",       "MAD",       "504",
    "YEMEN",               "Yemeni Rial",           "YER",       "886",
    "ZAMBIA",              "Zambian Kwacha",        "ZMW",       "967",
    "ZIMBABWE",            "Zimbabwe Dollar",       "ZWL",       "932",
    "ÅLAND ISLANDS",       "Euro",                  "EUR",       "978"
};

char * iso3166_2_country_codes[] = {
    "AD", "Andorra",
    "AE", "United Arab Emirates",
    "AF", "Afghanistan",
    "AG", "Antigua and Barbuda",
    "AI", "Anguilla",
    "AL", "Albania",
    "AM", "Armenia",
    "AO", "Angola",
    "AQ", "Antarctica",
    "AR", "Argentina",
    "AS", "American Samoa",
    "AT", "Austria",
    "AU", "Australia",
    "AW", "Aruba",
    "AX", "Åland Islands",
    "AZ", "Azerbaijan",
    "BA", "Bosnia and Herzegovina",
    "BB", "Barbados",
    "BD", "Bangladesh",
    "BE", "Belgium",
    "BF", "Burkina Faso",
    "BG", "Bulgaria",
    "BH", "Bahrain",
    "BI", "Burundi",
    "BJ", "Benin",
    "BL", "Saint Barthélemy",
    "BM", "Bermuda",
    "BN", "Brunei Darussalam",
    "BO", "Bolivia, Plurinational State of",
    "BQ", "Bonaire, Sint Eustatius and Saba",
    "BR", "Brazil",
    "BS", "Bahamas",
    "BT", "Bhutan",
    "BV", "Bouvet Island",
    "BW", "Botswana",
    "BY", "Belarus",
    "BZ", "Belize",
    "CA", "Canada",
    "CC", "Cocos (Keeling) Islands",
    "CD", "Congo, Democratic Republic of the",
    "CF", "Central African Republic",
    "CG", "Congo",
    "CH", "Switzerland",
    "CI", "Côte d'Ivoire",
    "CK", "Cook Islands",
    "CL", "Chile",
    "CM", "Cameroon",
    "CN", "China",
    "CO", "Colombia",
    "CR", "Costa Rica",
    "CU", "Cuba",
    "CV", "Cabo Verde",
    "CW", "Curaçao",
    "CX", "Christmas Island",
    "CY", "Cyprus",
    "CZ", "Czechia",
    "DE", "Germany",
    "DJ", "Djibouti",
    "DK", "Denmark",
    "DM", "Dominica",
    "DO", "Dominican Republic",
    "DZ", "Algeria",
    "EC", "Ecuador",
    "EE", "Estonia",
    "EG", "Egypt",
    "EH", "Western Sahara",
    "ER", "Eritrea",
    "ES", "Spain",
    "ET", "Ethiopia",
    "FI", "Finland",
    "FJ", "Fiji",
    "FK", "Falkland Islands",
    "FM", "Micronesia, Federated States of",
    "FO", "Faroe Islands",
    "FR", "France",
    "GA", "Gabon",
    "GB", "United Kingdom",
    "GD", "Grenada",
    "GE", "Georgia",
    "GF", "French Guiana",
    "GG", "Guernsey",
    "GH", "Ghana",
    "GI", "Gibraltar",
    "GL", "Greenland",
    "GM", "Gambia",
    "GN", "Guinea",
    "GP", "Guadeloupe",
    "GQ", "Equatorial Guinea",
    "GR", "Greece",
    "GS", "South Georgia and the South Sandwich Islands",
    "GT", "Guatemala",
    "GU", "Guam",
    "GW", "Guinea-Bissau",
    "GY", "Guyana",
    "HK", "Hong Kong",
    "HM", "Heard Island and McDonald Islands",
    "HN", "Honduras",
    "HR", "Croatia",
    "HT", "Haiti",
    "HU", "Hungary",
    "ID", "Indonesia",
    "IE", "Ireland",
    "IL", "Israel",
    "IM", "Isle of Man",
    "IN", "India",
    "IO", "British Indian Ocean Territory",
    "IQ", "Iraq",
    "IR", "Iran",
    "IS", "Iceland",
    "IT", "Italy",
    "JE", "Jersey",
    "JM", "Jamaica",
    "JO", "Jordan",
    "JP", "Japan",
    "KE", "Kenya",
    "KG", "Kyrgyzstan",
    "KH", "Cambodia",
    "KI", "Kiribati",
    "KM", "Comoros",
    "KN", "Saint Kitts and Nevis",
    "KP", "Korea, Democratic People's Republic of",
    "KR", "Korea, Republic of",
    "KW", "Kuwait",
    "KY", "Cayman Islands",
    "KZ", "Kazakhstan",
    "LA", "Lao People's Democratic Republic",
    "LB", "Lebanon",
    "LC", "Saint Lucia",
    "LI", "Liechtenstein",
    "LK", "Sri Lanka",
    "LR", "Liberia",
    "LS", "Lesotho",
    "LT", "Lithuania",
    "LU", "Luxembourg",
    "LV", "Latvia",
    "LY", "Libya",
    "MA", "Morocco",
    "MC", "Monaco",
    "MD", "Moldova, Republic of",
    "ME", "Montenegro",
    "MF", "Saint Martin (French part)",
    "MG", "Madagascar",
    "MH", "Marshall Islands",
    "MK", "North Macedonia",
    "ML", "Mali",
    "MM", "Myanmar",
    "MN", "Mongolia",
    "MO", "Macao",
    "MP", "Northern Mariana Islands",
    "MQ", "Martinique",
    "MR", "Mauritania",
    "MS", "Montserrat",
    "MT", "Malta",
    "MU", "Mauritius",
    "MV", "Maldives",
    "MW", "Malawi",
    "MX", "Mexico",
    "MY", "Malaysia",
    "MZ", "Mozambique",
    "NA", "Namibia",
    "NC", "New Caledonia",
    "NE", "Niger",
    "NF", "Norfolk Island",
    "NG", "Nigeria",
    "NI", "Nicaragua",
    "NL", "Netherlands, Kingdom of the",
    "NO", "Norway",
    "NP", "Nepal",
    "NR", "Nauru",
    "NU", "Niue",
    "NZ", "New Zealand",
    "OM", "Oman",
    "PA", "Panama",
    "PE", "Peru",
    "PF", "French Polynesia",
    "PG", "Papua New Guinea",
    "PH", "Philippines",
    "PK", "Pakistan",
    "PL", "Poland",
    "PM", "Saint Pierre and Miquelon",
    "PN", "Pitcairn",
    "PR", "Puerto Rico",
    "PS", "Palestine, State of",
    "PT", "Portugal",
    "PW", "Palau",
    "PY", "Paraguay",
    "QA", "Qatar",
    "RE", "Réunion",
    "RO", "Romania",
    "RS", "Serbia",
    "RU", "Russian Federation",
    "RW", "Rwanda",
    "SA", "Saudi Arabia",
    "SB", "Solomon Islands",
    "SC", "Seychelles",
    "SD", "Sudan",
    "SE", "Sweden",
    "SG", "Singapore",
    "SH", "Saint Helena, Ascension and Tristan da Cunha",
    "SI", "Slovenia",
    "SJ", "Svalbard and Jan Mayen",
    "SK", "Slovakia",
    "SL", "Sierra Leone",
    "SM", "San Marino",
    "SN", "Senegal",
    "SO", "Somalia",
    "SR", "Suriname",
    "SS", "South Sudan",
    "ST", "Sao Tome and Principe",
    "SV", "El Salvador",
    "SX", "Sint Maarten (Dutch part)",
    "SY", "Syrian Arab Republic",
    "SZ", "Eswatini",
    "TC", "Turks and Caicos Islands",
    "TD", "Chad",
    "TF", "French Southern Territories",
    "TG", "Togo",
    "TH", "Thailand",
    "TJ", "Tajikistan",
    "TK", "Tokelau",
    "TL", "Timor-Leste",
    "TM", "Turkmenistan",
    "TN", "Tunisia",
    "TO", "Tonga",
    "TR", "Türkiye",
    "TT", "Trinidad and Tobago",
    "TV", "Tuvalu",
    "TW", "Taiwan",
    "TZ", "Tanzania, United Republic of",
    "UA", "Ukraine",
    "UG", "Uganda",
    "UM", "United States Minor Outlying Islands",
    "US", "United States of America",
    "UY", "Uruguay",
    "UZ", "Uzbekistan",
    "VA", "Holy See",
    "VC", "Saint Vincent and the Grenadines",
    "VE", "Venezuela, Bolivarian Republic of",
    "VG", "Virgin Islands (British)",
    "VI", "Virgin Islands (U.S.)",
    "VN", "Vietnam",
    "VU", "Vanuatu",
    "WF", "Wallis and Futuna",
    "WS", "Samoa",
    "YE", "Yemen",
    "YT", "Mayotte",
    "ZA", "South Africa",
    "ZM", "Zambia",
    "ZW", "Zimbabwe"
};

/* UNECE meat carcasses and cuts code field 1 */
char * unece_species_code[] = {
    "10", "Bovine (Beef)",
    "11", "Bovine (Veal)",
    "30", "Porcine (Pork)",
    "40", "Ovine (Sheep)",
    "50", "Caprine (Goat)",
    "60", "Llama",
    "61", "Alpaca",
    "70", "Chicken",
    "71", "Turkey"
};

/* UNECE meat carcasses and cuts code field 2 */
char * unece_product_code[] = {
    "1643", "", "Brisket",
    "1650", "1653", "Brisket point end (Bone-in)",
    "1660", "1665", "Brisket navel end (Bone-in)",
    "1674", "", "Brisket point (sternum)",
    "1673", "", "Brisket rib plate",
    "1500", "1503", "Butt",
    "1510", "", "Butt - shank-off",
    "1502", "", "Butt and rump",
    "1520", "", "Butt square cut",
    "1001", "", "Carcase",
    "1622", "", "Chuck roll-long cut (Bone-in)",
    "1617", "", "Chuck - square cut",
    "1599", "", "Full Rib Set",
    "1063", "", "Forequarter",
    "1050", "", "Forequarter and flank (pistola forequarter)",
    "1680", "", "Forequarter / Hindquarter shin – shank",
    "1010", "", "Hindquarter",
    "1525", "", "Loin (bone-in)",
    "1630", "", "Neck",
    "1020", "", "Pistola",
    "1597", "", "Ribs",
    "1604", "", "Ribs-prepared",
    "1540", "", "Rump and loin",
    "1694", "", "Short ribs",
    "1550", "", "Shortloin",
    "1626", "", "Shoulder and foreleg",
    "1000", "", "Side",
    "1695", "", "Spare ribs",
    "2300", "", "Boneless Blade (clod)",
    "2302", "", "Boneless Blade bolar",
    "2303", "", "Boneless Blade oyster",
    "2304", "", "Boneless Blade undercut",
    "2133", "", "Boneless Bottom sirloin butt, ball tip",
    "2323", "", "Boneless Brisket",
    "2330", "2333", "Brisket point end (Boneless)",
    "2340", "2345", "Brisket navel end (Boneless)",
    "2358", "", "Boneless Brisket deckle off",
    "2473", "", "Boneless Brisket navel plate",
    "2353", "", "Boneless Brisket point end deckle off",
    "2483", "", "Boneless Butt set",
    "2278", "", "Boneless Chuck crest",
    "2268", "", "Boneless Chuck eye roll",
    "2275", "", "Boneless Chuck roll",
    "2264", "", "Boneless Chuck eye",
    "2289", "", "Boneless Chuck roll - long cut",
    "2310", "", "Boneless Chuck tender",
    "2240", "", "Boneless Cube roll (rib eye roll)",
    "2196", "", "Boneless Cutaneus trunci (rose)",
    "2093", "", "Boneless Eye of rump",
    "2040", "", "Boneless Eye round",
    "2210", "", "Boneless Flank steak",
    "2360", "", "Boneless Shin - shank",
    "2364", "", "Boneless Heel muscle",
    "2010", "", "Boneless Inside",
    "2012", "", "Boneless Inside cap",
    "2011", "", "Boneless Inside - cap off",
    "2035", "", "Boneless Inside meat",
    "2205", "", "Boneless Inside skirt",
    "2203", "", "Boneless Internal flank plate",
    "2070", "", "Boneless Knuckle",
    "2146", "", "Boneless Loin",
    "2280", "", "Boneless Neck",
    "2030", "", "Boneless Outside",
    "2050", "", "Boneless Outside flat",
    "2033", "", "Boneless Outside meat",
    "2329", "", "Boneless Pectoral meat",
    "2090", "", "Boneless Rump",
    "2091", "", "Boneless Rump cap",
    "2229", "", "Boneless Rib eye cap meat",
    "2081", "", "Boneless Bottom sirloin butt",
    "2020", "", "Boneless Silverside",
    "2230", "", "Boneless Spencer roll",
    "2140", "", "Boneless Striploin",
    "2306", "", "Boneless Shoulder tender",
    "2150", "", "Boneless Tenderloin",
    "2160", "", "Boneless Tenderloin side strap off",
    "2060", "", "Boneless Thick flank",
    "2180", "", "Boneless Thick skirt (hanging tender)",
    "2200", "", "Boneless Thin flank",
    "2190", "", "Boneless Thin skirt (outside skirt)",
    "2120", "", "Boneless Top sirloin (top butt)",
    "2131", "", "Boneless Tri-tip"
};

/* Figure 7.9.5-1. GS1 AI encodable character reference values */
char * encodable_char_ref[] = {
    "!", "0",
    "\"", "1",
    "%", "2",
    "&", "3",
    "'", "4",
    "(", "5",
    ")", "6",
    "*", "7",
    "+", "8",
    ",", "9",
    "-", "10",
    "B", "30",
    "C", "31",
    "D", "32",
    "E", "33",
    "F", "34",
    "G", "35",
    "H", "36",
    "I", "37",
    "J", "38",
    "K", "39",
    "L", "40",
    "e", "60",
    "f", "61",
    "g", "62",
    "h", "63",
    "i", "64",
    "j", "65",
    "k", "66",
    "l", "67",
    "m", "68",
    "n", "69",
    "o", "70",
    ".", "11",
    "/", "12",
    "0", "13",
    "1", "14",
    "2", "15",
    "3", "16",
    "4", "17",
    "5", "18",
    "6", "19",
    "7", "20",
    "8", "21",
    "9", "22",
    ":", "23",
    ";", "24",
    "<", "25",
    "=", "26",
    ">", "27",
    "?", "28",
    "A", "29",
    "M", "41",
    "N", "42",
    "O", "43",
    "P", "44",
    "Q", "45",
    "R", "46",
    "S", "47",
    "T", "48",
    "U", "49",
    "V", "50",
    "W", "51",
    "X", "52",
    "Y", "53",
    "Z", "54",
    "_", "55",
    "a", "56",
    "b", "57",
    "c", "58",
    "d", "59",
    "p", "71",
    "q", "72",
    "r", "73",
    "s", "74",
    "t", "75",
    "u", "76",
    "v", "77",
    "w", "78",
    "x", "79",
    "y", "80",
    "z", "81"
};

/* Figure 7.9.5-2. Check character reference values */
char * check_char_ref[] = {
    "2", "0",
    "3", "1",
    "4", "2",
    "5", "3",
    "6", "4",
    "7", "5",
    "8", "6",
    "9", "7",
    "A", "8",
    "B", "9",
    "C", "10",
    "D", "11",
    "E", "12",
    "F", "13",
    "G", "14",
    "H", "15",
    "J", "16",
    "K", "17",
    "L", "18",
    "M", "19",
    "N", "20",
    "P", "21",
    "Q", "22",
    "R", "23",
    "S", "24",
    "T", "25",
    "U", "26",
    "V", "27",
    "W", "28",
    "X", "29",
    "Y", "30",
    "Z", "31"
};

/* fishing gear types as defined by
   United Nations Fisheries and Aquaculture Department of the Food and
   Agricultural Organization (FAO)
   See https://www.fao.org/fishery/geartype/search/en?page=1 */
char * fishing_gear_type[] = {
    "Aerial traps", "Traps", "08.6",
    "Barriers, fences, weirs, etc.", "Traps", "08.5",
    "Beach seines", "Seine nets", "02.1",
    "Beam trawls", "Trawls", "03.11",
    "Boat seines", "Seine nets", "02.2",
    "Boat-operated lift nets", "Lift nets", "05.2",
    "Bottom pair trawls", "Trawls", "03.15",
    "Bottom trawls (nei)", "Trawls", "03.19",
    "Cast nets", "Falling gear", "06.1",
    "Combined gillnets-trammel nets", "Gillnets and entangling nets", "07.6",
    "Cover pots/Lantern nets", "Falling gear", "06.2",
    "Diving", "Miscellaneous gears", "10.8",
    "Dredges", "Dredges", "04",
    "Dredges (nei)", "Dredges", "04.9",
    "Drift gillnets", "Gillnets and entangling nets", "07.2",
    "Drifting longlines", "Hooks and lines", "09.32",
    "Drive-in nets", "Miscellaneous gears", "10.7",
    "Electric fishing", "Miscellaneous gears", "10.4",
    "Encircling gillnets", "Gillnets and entangling nets", "07.3",
    "Falling gear", "Falling gear", "06",
    "Falling gear (nei)", "Falling gear", "06.9",
    "Fixed gillnets (on stakes)", "Gillnets and entangling nets", "07.4",
    "Fyke nets", "Traps", "08.3",
    "Gear nei", "Miscellaneous gears", "10.9",
    "Gear not known", "Gear not known", "99.9",
    "Gear not known", "Gear not known", "99",
    "Gillnets and entangling nets", "Gillnets and entangling nets", "07",
    "Gillnets and entangling nets (nei)", "Gillnets and entangling nets", "07.9",
    "Hand Implements (Wrenching gear, Clamps, Tongs, Rakes, Spears)", "Miscellaneous gears", "10.2",
    "Hand dredges", "Dredges", "04.2",
    "Handlines and hand-operated pole-and-lines", "Hooks and lines", "09.1",
    "Harpoons", "Miscellaneous gears", "10.1",
    "Hooks and lines", "Hooks and lines", "09",
    "Hooks and lines (nei)", "Hooks and lines", "09.9",
    "Lift nets", "Lift nets", "05",
    "Lift nets (nei)", "Lift nets", "05.9",
    "Longlines (nei)", "Hooks and lines", "09.39",
    "Mechanized dredges", "Dredges", "04.3",
    "Mechanized lines and pole-and-lines", "Hooks and lines", "09.2",
    "Midwater pair trawls", "Trawls", "03.22",
    "Midwater trawls (nei)", "Trawls", "03.29",
    "Multiple bottom otter trawls", "Trawls", "03.14",
    "Portable lift nets", "Lift nets", "05.1",
    "Pots", "Traps", "08.2",
    "Pumps", "Miscellaneous gears", "10.3",
    "Purse seines", "Surrounding nets", "01.1",
    "Pushnets", "Miscellaneous gears", "10.5",
    "Scoopnets", "Miscellaneous gears", "10.6",
    "Seine nets", "Seine nets", "02",
    "Seine nets (nei)", "Seine nets", "02.9",
    "Semipelagic trawls", "Trawls", "03.3",
    "Set gillnets (anchored)", "Gillnets and entangling nets", "07.1",
    "Set longlines", "Hooks and lines", "09.31",
    "Shore-operated stationary lift nets", "Lift nets", "05.3",
    "Single boat bottom otter trawls", "Trawls", "03.12",
    "Single boat midwater otter trawls", "Trawls", "03.21",
    "Stationary uncovered pound nets", "Traps", "08.1",
    "Stow nets", "Traps", "08.4",
    "Surrounding Nets without Purse Lines", "Surrounding nets", "01.2",
    "Surrounding nets", "Surrounding nets", "01",
    "Surrounding nets (nei)", "Surrounding nets", "01.9",
    "Towed dredges", "Dredges", "04.1",
    "Trammel nets", "Gillnets and entangling nets", "07.5",
    "Traps", "Traps", "08",
    "Traps (nei)", "Traps", "08.9",
    "Trawls", "Trawls", "03",
    "Trawls (nei)", "Trawls", "03.9",
    "Trolling lines", "Hooks and lines", "09.5",
    "Twin bottom otter trawls", "Trawls", "03.13",
    "Vertical lines", "Hooks and lines", "09.4"
};
